development:
  adapter: postgresql
  encoding: unicode
  database: moviepick_development
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: moviepick_production
  host: localhost
  pool: 5
  # username: eifion
  # password:
