# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66a4c8042d08ddd4a35817e7e06ab7877c3cce002ac0524e80f1b4ee5d6374e70b98beeee76a9005b06547db21b9e801f93ac30e2ffd6a8863a864151f17ffe9

test:
  secret_key_base: 2def6c4ca4a7ee1488ae902536205768e27ea5920cae414dff1c443588ad0fb4aea5a029126363d901d3c31c698b531f646e5f009b7a035924a3267e68c290a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
